services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=scrapy
      - POSTGRES_PASSWORD=P@ssw0rd!
      - POSTGRES_DB=scrapydb
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
